### PR TITLE
Added features | Solved bugs | 3 files are changed {More Details inside}

### PR DESCRIPTION
**Pull request by NomanBaigA**
1) Added permissions. because it was missing
2) constants_ignore.dart is not exist so I commented out the unused code
3) Added new features so now we can set wallpapers as - Home Screen, Lock Screen and both

Changes are done in these 3 files
- android/app/src/main/AndroidManifest.xml
- lib/api/api.dart
- lib/pages/image_detail.dart

### CODE REVIEW

**Comment by asiflatif** [comment]
Thanks for your contribution. Let me have a test on my physical device.

**Comment by NomanBaigA** [comment]
> Thanks for your contribution. Let me have a test on my physical device.

sure :)

**Comment by NomanBaigA** [comment]
> Thanks for your contribution. Let me have a test on my physical device.

To compile and run it successfully you have to use an older flutter version. I used "Flutter 2.2.3"

**Review by asiflatif — APPROVED** [review]
Working fine. 
Since `wallpaper_manager` package is not supporting Flutter 3, workaround to fix the potential error is [this](https://github.com/AdityaMulgundkar/wallpaper_manager/issues/32#issuecomment-1189346840).

**Pull request merged**
